### PR TITLE
update the gpt3.5 answer with 2Ktokens and fix bug of format

### PR DESCRIPTION
**Pull request by hitoshizuku7**
## Why are these changes needed?

Update the GPT3.5 davinci answer with 2K max tokens.

And now the format of the answers generated by GPT3.5 davinci is jsonl, but not json.

#31

### CODE REVIEW

**Review by hkiyomaru — COMMENTED** [review]
Can you please rename the model ID to `openai--text-davinci-003`? Since Davinci has several versions, this is more specific.

**Comment by hkiyomaru** [comment]
You don't need to rerun the code; just replace the model ID.

**Comment by hitoshizuku7** [comment]
> You don't need to rerun the code; just replace the model ID.

I have done it. 
And delate the useless model answer files.

**Comment by hkiyomaru** [comment]
Some model answer files (e.g., `Llama-2-7b-hf.jsonl`) lack corresponding configuration files. Can you either provide configuration files for these answer files, or remove the answer files that are missing their configurations?"

**Comment by hitoshizuku7** [comment]
> Some model answer files (e.g., `Llama-2-7b-hf.jsonl`) lack corresponding configuration files. Can you either provide configuration files for these answer files, or remove the answer files that are missing their configurations?"

Sorry for hurry merge. 
These answers (e.g., `Llama-2-7b-hf.jsonl` ) are generated with lora model. And these answers will be used as performance evaluation on README part. 
So could I update the config file with lora model version? Because the lora model is save on local, should I share it?

**Pull request merged**
